
'use client';

import { useFormContext, useWatch } from 'react-hook-form';
import { type ResumeSchema } from '@/lib/schemas';
import { Card, CardContent } from '@/components/ui/card';
import { FileText } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Skeleton } from './ui/skeleton';
import { dynamicTemplates } from '@/components/templates/template-map';

export function ResumePreview() {
  const { control } = useFormContext<ResumeSchema>();
  const data = useWatch({ control });

  // The form's default values ensure `data` is always structured correctly.
  // We can show a skeleton briefly if data isn't fully hydrated on the very first render.
  if (!data?.template) {
    return (
      <div className="h-full w-full overflow-hidden p-8">
        <Skeleton className="w-full h-full" />
      </div>
    );
  }

  const { coverLetter, template } = data;

  const SelectedTemplate = dynamicTemplates[template] || dynamicTemplates.modern;

  return (
    <Card className="h-full w-full overflow-hidden shadow-lg print:shadow-none print:border-none">
      <CardContent className="h-full p-0">
        <Tabs defaultValue="resume" className="flex h-full flex-col">
          <TabsList className="mx-4 mt-4 shrink-0 print:hidden">
            <TabsTrigger value="resume">
              <FileText className="mr-2 h-4 w-4" /> Resume
            </TabsTrigger>
            <TabsTrigger value="cover-letter">
              <FileText className="mr-2 h-4 w-4" /> Cover Letter
            </TabsTrigger>
          </TabsList>
          <div className="flex-1 overflow-y-auto bg-muted/30 print:bg-transparent">
            <TabsContent value="resume" className="m-0 resume-content-wrapper">
                <div className="my-8 mx-auto bg-white text-gray-900 shadow-lg" style={{width: '210mm'}}>
                    <SelectedTemplate data={data} />
                </div>
            </TabsContent>
            <TabsContent value="cover-letter" className="m-0 cover-letter-content-wrapper">
                <div className="my-8 mx-auto bg-white text-gray-900 shadow-lg" style={{width: '210mm', minHeight: '297mm'}}>
                    <div className="p-6 sm:p-8">
                    {coverLetter ? (
                        <>
                        <div className="whitespace-pre-wrap font-body text-sm">
                            {coverLetter}
                        </div>
                        <div className="mt-6 text-center text-xs text-muted-foreground">
                            <p className="italic">
                            This cover letter was generated by AI. Please review
                            and edit carefully before sending.
                            </p>
                        </div>
                        </>
                    ) : (
                        <div className="flex h-96 items-center justify-center text-center text-gray-500">
                        <div className="space-y-2">
                            <FileText size={48} className="mx-auto" />
                            <p>Your generated cover letter will appear here.</p>
                            <p className="text-xs">
                            Go to the "AI Cover Letter Generator" section to
                            create one.
                            </p>
                        </div>
                        </div>
                    )}
                    </div>
                </div>
            </TabsContent>
          </div>
        </Tabs>
      </CardContent>
    </Card>
  );
}
