# This GitHub Actions workflow automates the process of building the Ollama proxy executable
# and publishing it to a GitHub Release.
name: Build and Release Ollama Proxy

on:
  # This workflow now runs on every push to the main branch to ensure reliability.
  # The 'paths' filter has been temporarily removed for debugging.
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release Executables
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install 'pkg', the tool that creates the executables
      - name: Install pkg
        run: npm install -g pkg

      # 4. Run pkg to build the executables for Windows, macOS, and Linux
      - name: Build executables with pkg
        run: |
          mkdir -p dist
          pkg ollama-proxy.js --targets node18-win-x64 --output dist/ollama-proxy-win.exe
          pkg ollama-proxy.js --targets node18-macos-x64 --output dist/ollama-proxy-macos
          pkg ollama-proxy.js --targets node18-linux-x64 --output dist/ollama-proxy-linux
          chmod +x dist/ollama-proxy-macos dist/ollama-proxy-linux

      # 5. Create or update a GitHub Release with the executables
      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # This token is provided by GitHub Actions. No secret needed.
          token: ${{ secrets.GITHUB_TOKEN }}
          # The tag for this release. Using 'latest' will overwrite the previous 'latest' release.
          tag_name: latest
          # The name of the release in the GitHub UI.
          name: Latest Ollama Proxy
          # A description for the release.
          body: |
            This release contains the latest compiled executables for the Ollama proxy.
            Download the appropriate file for your operating system.
          # The files to upload to the release.
          files: |
            dist/ollama-proxy-win.exe
            dist/ollama-proxy-macos
            dist/ollama-proxy-linux
